## Contents

<ol><li>Use of builtin methods vs. Series Iteration</li>
    <ol><li>sum</li>
        <li>"+="</li>
        </ol>
    <li>Set Index</li>
</ol>

In [1]:
import numpy as np
import pandas as pd

pd.set_option('max_colwidth', 100)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.float_format', lambda x: '{:,.2f}'.format(x))

In [2]:
df = pd.read_csv('git_repo/Data-Science-Python------Coursera-MICHIGAN-/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,NPOPCHG_2010,NPOPCHG_2011,NPOPCHG_2012,NPOPCHG_2013,NPOPCHG_2014,NPOPCHG_2015,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,DEATHS2010,DEATHS2011,DEATHS2012,DEATHS2013,DEATHS2014,DEATHS2015,NATURALINC2010,NATURALINC2011,NATURALINC2012,NATURALINC2013,NATURALINC2014,NATURALINC2015,INTERNATIONALMIG2010,INTERNATIONALMIG2011,INTERNATIONALMIG2012,INTERNATIONALMIG2013,INTERNATIONALMIG2014,INTERNATIONALMIG2015,DOMESTICMIG2010,DOMESTICMIG2011,DOMESTICMIG2012,DOMESTICMIG2013,DOMESTICMIG2014,DOMESTICMIG2015,NETMIG2010,NETMIG2011,NETMIG2012,NETMIG2013,NETMIG2014,NETMIG2015,RESIDUAL2010,RESIDUAL2011,RESIDUAL2012,RESIDUAL2013,RESIDUAL2014,RESIDUAL2015,GQESTIMATESBASE2010,GQESTIMATES2010,GQESTIMATES2011,GQESTIMATES2012,GQESTIMATES2013,GQESTIMATES2014,GQESTIMATES2015,RBIRTH2011,RBIRTH2012,RBIRTH2013,RBIRTH2014,RBIRTH2015,RDEATH2011,RDEATH2012,RDEATH2013,RDEATH2014,RDEATH2015,RNATURALINC2011,RNATURALINC2012,RNATURALINC2013,RNATURALINC2014,RNATURALINC2015,RINTERNATIONALMIG2011,RINTERNATIONALMIG2012,RINTERNATIONALMIG2013,RINTERNATIONALMIG2014,RINTERNATIONALMIG2015,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,4801108,4816089,4830533,4846411,4858979,5034,15947,14981,14444,15878,12568,14226,59689,59062,57938,58334,58305,11089,48811,48357,50843,50228,50330,3137,10878,10705,7095,8106,7975,1357,4926,4904,4834,5529,5726,537,11,-929,1838,2816,-2268,1894,4937,3975,6672,8345,3458,3,132,301,677,-573,1135,116185,116212,115560,115666,116963,119088,119599,12.45,12.28,12.01,12.06,12.01,10.18,10.06,10.54,10.38,10.37,2.27,2.23,1.47,1.68,1.64,1.03,1.02,1.00,1.14,1.18,0.00,-0.19,0.38,0.58,-0.47,1.03,0.83,1.38,1.72,0.71
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,55253,55175,55038,55290,55347,89,593,-78,-137,252,57,151,636,615,574,623,600,152,507,558,583,504,467,-1,129,57,-9,119,133,33,20,16,16,18,19,49,398,-161,-166,125,-140,82,418,-145,-150,143,-121,8,46,10,22,-10,45,455,455,455,455,455,455,455,11.57,11.14,10.42,11.29,10.85,9.23,10.11,10.58,9.14,8.44,2.35,1.03,-0.16,2.16,2.40,0.36,0.29,0.29,0.33,0.34,7.24,-2.92,-3.01,2.27,-2.53,7.61,-2.63,-2.72,2.59,-2.19
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,186659,190396,195126,199713,203709,928,3466,3737,4730,4587,3996,517,2187,2092,2160,2186,2240,532,1825,1879,1902,2044,1992,-15,362,213,258,142,248,69,187,172,170,212,221,856,2743,3327,4211,3799,3469,925,2930,3499,4381,4011,3690,18,174,25,91,434,58,2307,2307,2307,2249,2304,2308,2309,11.83,11.10,11.21,11.07,11.10,9.87,9.97,9.87,10.35,9.88,1.96,1.13,1.34,0.72,1.23,1.01,0.91,0.88,1.07,1.10,14.83,17.65,21.85,19.24,17.20,15.84,18.56,22.73,20.32,18.29
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,27226,27159,26973,26815,26489,-116,-115,-67,-186,-158,-326,70,335,300,283,260,269,128,319,291,294,310,309,-58,16,9,-11,-50,-40,2,-4,-7,-3,-2,0,-62,-129,-68,-191,-105,-281,-60,-133,-75,-194,-107,-281,2,2,-1,19,-1,-5,3193,3193,3382,3388,3389,3353,3352,12.28,11.03,10.46,9.67,10.09,11.69,10.70,10.86,11.53,11.59,0.59,0.33,-0.41,-1.86,-1.50,-0.15,-0.26,-0.11,-0.07,0.00,-4.73,-2.50,-7.06,-3.90,-10.54,-4.87,-2.76,-7.17,-3.98,-10.54
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,22733,22642,22512,22549,22583,-58,-128,-91,-130,37,34,44,266,245,259,247,253,34,278,237,281,211,223,10,-12,8,-22,36,30,2,10,16,18,21,21,-69,-126,-115,-140,-4,4,-67,-116,-99,-122,17,25,-1,0,0,14,-16,-21,2224,2224,2224,2224,2224,2233,2236,11.67,10.80,11.47,10.96,11.21,12.19,10.45,12.45,9.37,9.88,-0.53,0.35,-0.97,1.60,1.33,0.44,0.71,0.80,0.93,0.93,-5.53,-5.07,-6.20,-0.18,0.18,-5.09,-4.36,-5.40,0.75,1.11

In [3]:
np.nan == None

False

In [4]:
df.loc[0, 'SUMLEV']

40

### Use of builtin methods vs Series Iteration

#### sum

In [17]:
s = pd.Series(np.random.randint(0,1000,10000))

In [30]:
%%timeit -n 100
total = 0
for item in s:
    total += item

1.34 ms ± 86.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [13]:
%%timeit -n 100
SUM = s.sum()

73.3 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

#### "+="

In [32]:
%%timeit -n 3
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label] = value+2

909 ms ± 39.8 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)

In [33]:
%%timeit -n 3
s = pd.Series(np.random.randint(0,1000,10000))
s += 2

491 µs ± 164 µs per loop (mean ± std. dev. of 7 runs, 3 loops each)

### Set Index

In [42]:
company_1 = pd.Series({'Company Name':'Google','Service':'Search Engine', 'Website':'www.google.com'})
company_2 = pd.Series({'Company Name':'Facebook','Service':'Social Network', 'Website':'www.facebook.com'})
company_3 = pd.Series({'Company Name':'Amazon','Service':'E-commerce', 'Website':'www.amazon.com'})

df = pd.DataFrame([company_1, company_2, company_3], index=['0','1','2'])
df

  Company Name         Service           Website
0       Google   Search Engine    www.google.com
1     Facebook  Social Network  www.facebook.com
2       Amazon      E-commerce    www.amazon.com

In [46]:
df.set_index('Service')

               Company Name           Website
Service
Search Engine        Google    www.google.com
Social Network     Facebook  www.facebook.com
E-commerce           Amazon    www.amazon.com